import type { SerpGoogleLocalResponse } from './schemas.js';

/** 5 profils « Diamant » (zone + avis + note, sans site) — une page suffit en simulation. */
export const MOCK_SERP_GOOGLE_LOCAL_RESPONSE: SerpGoogleLocalResponse = {
  search_metadata: {
    id: 'mock-search-id',
    status: 'Success',
    created_at: '2026-05-02T10:00:00Z',
    processed_at: '2026-05-02T10:00:01Z',
    total_time_taken: 0.42,
  },
  search_parameters: {
    engine: 'google_local',
    q: 'boulangerie artisanale',
    location: 'Haute-Savoie, France',
    google_domain: 'google.com',
    hl: 'fr',
    gl: 'fr',
  },
  local_results: [
    {
      position: 1,
      title: 'Le Fournil d’Annecy (mock D1)',
      place_id: 'ChIJdiam000000000000000000001',
      gps_coordinates: { latitude: 45.8992, longitude: 6.1294 },
      type: 'bakery',
      types: ['bakery'],
      address: '14 rue Sommeiller, 74000 Annecy',
      phone: '+33 4 00 00 00 01',
      rating: 4.6,
      reviews: 132,
      open_state: 'Ouvert',
      thumbnail: 'https://example.test/maps-cover-mock-annecy.jpg',
      place_review_texts: [
        'Super produits mais le samedi la file avance très lentement devant les vitrines.',
        'Je rappelle plusieurs fois avant l’horaire et le téléphone ne décroche jamais sur le num affiché.',
        'Cher pour ce rapport qualité-prix même si bien cuits.',
      ],
    },
    {
      position: 2,
      title: 'Pain & Lac — Cran-Gevrier (mock D2)',
      place_id: 'ChIJdiam000000000000000000002',
      gps_coordinates: { latitude: 45.9167, longitude: 6.1097 },
      type: 'bakery',
      types: ['bakery'],
      address: '42 avenue de Cran, 74960 Annecy',
      rating: 4.55,
      reviews: 88,
    },
    {
      position: 3,
      title: 'Maison Chambéry Pains (mock D3)',
      place_id: 'ChIJdiam000000000000000000003',
      gps_coordinates: { latitude: 45.5646, longitude: 5.9178 },
      type: 'bakery',
      types: ['bakery'],
      address: '6 rue de Boigne, 73000 Chambéry',
      rating: 4.5,
      reviews: 210,
    },
    {
      position: 4,
      title: 'Le Levain Grand Annecy (mock D4)',
      place_id: 'ChIJdiam000000000000000000004',
      gps_coordinates: { latitude: 45.9156, longitude: 6.1526 },
      type: 'bakery',
      types: ['bakery'],
      address: 'ZA des Épagny, 74370 Annecy',
      rating: 4.45,
      reviews: 95,
    },
    {
      position: 5,
      title: 'Bois du Pain — Bassens Chambéry (mock D5)',
      place_id: 'ChIJdiam000000000000000000005',
      gps_coordinates: { latitude: 45.5734, longitude: 5.9361 },
      type: 'bakery',
      types: ['bakery'],
      address: 'Chemin des Gaillards, 73000 Bassens',
      rating: 4.35,
      reviews: 67,
    },
  ],
};
